version: "2"
services:
  app:
    container_name: app
    image: binoykalathiparambil/springboot-mongo
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"